<template>
<div class="center">
  <div class="signup">
    
    <h2>Manage Your Account.</h2>

    <form v-on:submit.prevent="signup">
          <input class="email" v-bind:class="{ 'is-danger': invalidEmail }" type="email" placeholder="Your Email" v-model="email">
        <p class="error" v-if="invalidEmail">This email is invalid</p>

          <input class="password" v-bind:class="{ 'is-danger': invalidPassword }" type="password" placeholder="Your Password" v-model="password">
        <p class="error" v-if="invalidPassword">This password is invalid</p>

  
        <button type="submit" class="login">Log In</button>

    </form>

  </div>

        <div class="form-group">
        <div class="flash flash-error" v-if="formError.length > 0" v-text="formError"></div>
      </div>

      </div>

</template>

<script>
import GoogleButton from '~/components/account/3rd-party/GoogleButton.vue'
import GithubButton from '~/components/account/3rd-party/GithubButton.vue'

export default {
  name: 'LoginForm',
  components: {
    GoogleButton,
    GithubButton
  },
  data () {
    return {
      email: '',
      password: '',
      formError: ''
    }
  },
  computed: {
    invalidEmail () {
      return false // !this.email.includes('@')
    },
    invalidPassword () {
      return false // !this.password.length > 12
    }
  },
  methods: {
    signup () {
      this.formError = ''
      this.$store.dispatch('userLogin', {
        email: this.email,
        password: this.password
      })
        .then(() => {
          this.$router.push('/account/dashboard')
        })
        .catch((error) => {
          console.log(error)
          this.formError = error.message
        })
    }
  }
}
</script>
<style lang="sass" scoped>
.center
  display: flex
  justify-content: center
  align-items: center
  height: 100vh

/* ----------------------------------------------
 * Generated by Animista on 2019-1-22 16:4:10
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-vertical-fwd
 * ----------------------------------------
 */


@keyframes flipInX
  from
    -webkit-transform: perspective(400px) rotate3d(1, 0, 0, 90deg)
    transform: perspective(400px) rotate3d(1, 0, 0, 90deg)
    -webkit-animation-timing-function: ease-in
    animation-timing-function: ease-in
    opacity: 0

  40%
    -webkit-transform: perspective(400px) rotate3d(1, 0, 0, -20deg)
    transform: perspective(400px) rotate3d(1, 0, 0, -20deg)
    -webkit-animation-timing-function: ease-in
    animation-timing-function: ease-in

  60%
    -webkit-transform: perspective(400px) rotate3d(1, 0, 0, 10deg)
    transform: perspective(400px) rotate3d(1, 0, 0, 10deg)
    opacity: 1

  80%
    -webkit-transform: perspective(400px) rotate3d(1, 0, 0, -5deg)
    transform: perspective(400px) rotate3d(1, 0, 0, -5deg)

  to
    -webkit-transform: perspective(400px)
    transform: perspective(400px)
    opacity: 1
  

.signup
  background: #fff
  border-radius: 20px
  box-shadow: 0 0px 20px rgba(0,0,0,0.1)
  height: auto
  padding: 0px
  margin: 7% 0 0 0
  animation: flipInX 1.2s cubic-bezier(0.455, 0.030, 0.515, 0.955) forwards
  animation-delay: .2s !important
  display: block
  opacity: 0
  max-width: 35%
  position: relative
  h2
    background: url("data:image/svg+xml,%3Csvg width='176' height='176' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Cdefs%3E%3Cpath id='b' d='M52 0l47 94H5z'/%3E%3Cfilter x='-.5%25' y='-.5%25' width='101.1%25' height='102.1%25' filterUnits='objectBoundingBox' id='a'%3E%3CfeOffset dy='1' in='SourceAlpha' result='shadowOffsetOuter1'/%3E%3CfeColorMatrix values='0 0 0 0 0.676791029 0 0 0 0 0.676791029 0 0 0 0 0.676791029 0 0 0 0.5 0' in='shadowOffsetOuter1'/%3E%3C/filter%3E%3C/defs%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Ccircle fill='%235ABBAA' cx='88' cy='88' r='88'/%3E%3Cg transform='translate(36 38)'%3E%3Cuse fill='%23000' filter='url(%23a)' xlink:href='%23b'/%3E%3Cuse fill='%23FFF' xlink:href='%23b'/%3E%3C/g%3E%3Cpath d='M58.5 98.5L146 135M36.5 134.5l83-35' stroke='%235ABBAA' stroke-width='4' stroke-linecap='square'/%3E%3C/g%3E%3C/svg%3E") no-repeat center 15px
    background-size: 50px
    color: #5abbaa
    width: 100%
    border-radius: 30px 30px 0 0
    padding: 68px 20px 15px
    text-align: center
    margin: 10px 0 0px !important
    border-bottom: 1px solid rgba(0,0,0,0.07)

input 
  height: 100%
  padding: 20px 30px 20px 80px
  width: 100% !important
  margin: 0 !important
  color: rgba(90, 187, 170, 1.0000)
  background: rgba(248, 250, 250, 1.0000)
  border: none
  font-weight: 500
  border-bottom: 1px solid rgba(0,0,0,0.06)
  border-radius: 0 !important
  font-size: 1.35em
  transition: background .4s ease
  box-shadow: none
  &:focus 
    outline: 0 !important
    background: rgba(0,0,0,0.04)
  ~ input
    border: none !important
  
.password
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 375'%3E%3Cpath fill='rgba(0,0,0,0.3)' d='M150 161.5a15.6 15.6 0 0 0-7.8 29V208h15.6v-17.3a15.6 15.6 0 0 0-7.8-29.1zM150 85.8a23.8 23.8 0 0 0-23.8 23.8V135h47.6v-25.3A23.8 23.8 0 0 0 150 85.8z'/%3E%3Cpath fill='rgba(0,0,0,0.3)' d='M150 0a150 150 0 1 0 0 300 150 150 0 0 0 0-300zm46 227.1h-92c-9.8 0-17.7-7.9-17.7-17.6v-57c0-8.4 6-15.5 14-17.2v-25.7a49.8 49.8 0 0 1 99.4 0v25.7c8 1.7 14 8.8 14 17.3v56.9c0 9.7-7.9 17.6-17.6 17.6z'/%3E%3C/svg%3E") no-repeat 30px 15px !important
  background-size: 35px !important
  transition: padding .6s ease
.password:focus
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 375'%3E%3Cpath fill='rgba(90, 187, 170, 1.0000)' d='M150 161.5a15.6 15.6 0 0 0-7.8 29V208h15.6v-17.3a15.6 15.6 0 0 0-7.8-29.1zM150 85.8a23.8 23.8 0 0 0-23.8 23.8V135h47.6v-25.3A23.8 23.8 0 0 0 150 85.8z'/%3E%3Cpath fill='rgba(90, 187, 170, 1.0000)' d='M150 0a150 150 0 1 0 0 300 150 150 0 0 0 0-300zm46 227.1h-92c-9.8 0-17.7-7.9-17.7-17.6v-57c0-8.4 6-15.5 14-17.2v-25.7a49.8 49.8 0 0 1 99.4 0v25.7c8 1.7 14 8.8 14 17.3v56.9c0 9.7-7.9 17.6-17.6 17.6z'/%3E%3C/svg%3E") no-repeat 30px 15px !important
  background-size: 35px !important
.email
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' data-name='Layer 1' viewBox='0 0 100 125'%3E%3Cpath fill='rgba(0,0,0,0.3)' d='M50 100A50 50 0 1 0 0 50a50 50 0 0 0 50 50zM25.7 36a7.6 7.6 0 0 1 7.3-4.7h34a7.7 7.7 0 0 1 7.3 4.4 1.4 1.4 0 0 1-.8 2.1L51 49.6a1.9 1.9 0 0 1-1.9 0L26.3 37.7a1.2 1.2 0 0 1-.6-1.8zm1.5 7.4l21.2 11.1a3 3 0 0 0 3.2 0l21.2-11a2.4 2.4 0 0 1 .6-.2 1.2 1.2 0 0 1 1.6 1.2v14.2a22.3 22.3 0 0 1-.1 3.6 7.6 7.6 0 0 1-7.7 6.5H33a7.7 7.7 0 0 1-7.6-5.8 7.8 7.8 0 0 1-.3-2V44.7c0-1.4.9-2 2.1-1.3z'/%3E%3C/svg%3E") no-repeat 30px 15px
  background-size: 35px !important
  transition: padding .6s ease
.email:focus
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' data-name='Layer 1' viewBox='0 0 100 125'%3E%3Cpath fill='rgba(90, 187, 170, 1.0000)' d='M50 100A50 50 0 1 0 0 50a50 50 0 0 0 50 50zM25.7 36a7.6 7.6 0 0 1 7.3-4.7h34a7.7 7.7 0 0 1 7.3 4.4 1.4 1.4 0 0 1-.8 2.1L51 49.6a1.9 1.9 0 0 1-1.9 0L26.3 37.7a1.2 1.2 0 0 1-.6-1.8zm1.5 7.4l21.2 11.1a3 3 0 0 0 3.2 0l21.2-11a2.4 2.4 0 0 1 .6-.2 1.2 1.2 0 0 1 1.6 1.2v14.2a22.3 22.3 0 0 1-.1 3.6 7.6 7.6 0 0 1-7.7 6.5H33a7.7 7.7 0 0 1-7.6-5.8 7.8 7.8 0 0 1-.3-2V44.7c0-1.4.9-2 2.1-1.3z'/%3E%3C/svg%3E") no-repeat 30px 15px

input:-webkit-autofill
  background: #fff
  &:hover, &:focus, &:active
    background: #fff
    background-size: 35px !important

input:-webkit-autofill
  -webkit-animation: autofill 0s forwards
  animation: autofill 0s forwards
  &:hover, &:focus, &:active
    -webkit-animation: autofill 0s forwards
    animation: autofill 0s forwards

@keyframes autofill
  100%
    background: transparent
    color: inherit


@-webkit-keyframes autofill
  100%
    background: transparent
    color: inherit
    
.password:-webkit-autofill
  -webkit-box-shadow: 0 80px 0 0px white inset
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 375'%3E%3Cpath fill='rgba(0,0,0,0.3)' d='M150 161.5a15.6 15.6 0 0 0-7.8 29V208h15.6v-17.3a15.6 15.6 0 0 0-7.8-29.1zM150 85.8a23.8 23.8 0 0 0-23.8 23.8V135h47.6v-25.3A23.8 23.8 0 0 0 150 85.8z'/%3E%3Cpath fill='rgba(0,0,0,0.3)' d='M150 0a150 150 0 1 0 0 300 150 150 0 0 0 0-300zm46 227.1h-92c-9.8 0-17.7-7.9-17.7-17.6v-57c0-8.4 6-15.5 14-17.2v-25.7a49.8 49.8 0 0 1 99.4 0v25.7c8 1.7 14 8.8 14 17.3v56.9c0 9.7-7.9 17.6-17.6 17.6z'/%3E%3C/svg%3E") no-repeat 30px 15px !important
  background-size: 35px !important

.login
  width: 100%
  border: none
  background: rgba(255, 255, 255, 1.0000)
  margin: 0
  font-size: 1.45em
  font-weight: bold
  text-align: center
  padding: 12px 0 13px
  color: #5abbaa
  border-radius: 0 0 20px 20px
  border-top: 1px solid rgba(0,0,0,0.07)
  transition: background 1s ease

</style>
